name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  release: # * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [released]
  push:
    branches: [main]
    tags:
      - "v*.*.*"
    paths:
      # NOTE: Path filters are ignored for tag pushes
      - "src/services/image_recognition/**"
      - "tests/image_recognition/**"
      - ".github/workflows/github-actions-demo.yml"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/heads/main' && github.event_name == 'push'}}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
